FROM chirayukong/py-causal-notebook

MAINTAINER "Chirayu Kong Wongchokprasitti" chw20@pitt.edu

# smoke test that it's importable at least
RUN sh /usr/local/bin/start-singleuser.sh -h
CMD ["sh", "/usr/local/bin/start-singleuser.sh"]